export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#131315",
        "tertiary-fixed": "#ffddb1",
        "inverse-surface": "#e5e1e4",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#004e60",
        "on-secondary-fixed": "#310048",
        "surface-tint": "#4cd6ff",
        "inverse-on-surface": "#313032",
        "on-primary-fixed": "#001f28",
        "on-secondary-fixed-variant": "#7200a3",
        "tertiary-fixed-dim": "#ffba49",
        "on-tertiary-container": "#6b4700",
        "on-surface": "#e5e1e4",
        "on-error-container": "#ffdad6",
        "on-primary": "#003543",
        "on-primary-container": "#00566a",
        "on-tertiary-fixed": "#291800",
        "surface-bright": "#39393b",
        "on-tertiary-fixed-variant": "#624000",
        "secondary-fixed-dim": "#e9b3ff",
        "secondary-fixed": "#f6d9ff",
        "outline": "#859399",
        "surface-container": "#201f21",
        "primary-fixed": "#b7eaff",
        "surface-container-lowest": "#0e0e10",
        "error-container": "#93000a",
        "background": "#131315",
        "surface-container-high": "#2a2a2c",
        "surface-container-low": "#1c1b1d",
        "on-tertiary": "#442b00",
        "secondary-container": "#7d01b1",
        "on-secondary": "#510074",
        "primary-container": "#00d1ff",
        "on-surface-variant": "#bbc9cf",
        "inverse-primary": "#00677f",
        "primary": "#a4e6ff",
        "primary-fixed-dim": "#4cd6ff",
        "on-background": "#e5e1e4",
        "on-secondary-container": "#e5a9ff",
        "secondary": "#e9b3ff",
        "tertiary-container": "#feb127",
        "surface": "#131315",
        "surface-container-highest": "#353437",
        "outline-variant": "#3c494e",
        "error": "#ffb4ab",
        "surface-variant": "#353437",
        "tertiary": "#ffd59c",
        accent: '#00e5ff',
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
      borderRadius: {
        DEFAULT: "0.125rem", 
        lg: "0.25rem", 
        xl: "0.5rem", 
        full: "0.75rem"
      },
    },
  },
  plugins: [],
}